# Generated by Django 2.1.5 on 2019-01-25 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190125_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Eventa',
        ),
    ]
