# Generated by Django 2.1.5 on 2019-02-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeriya', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeriya',
            options={'ordering': ['-publish', 'id']},
        ),
        migrations.AddField(
            model_name='galeriya',
            name='publish',
            field=models.DateTimeField(default=1, verbose_name='Tarix'),
            preserve_default=False,
        ),
    ]
