# Generated by Django 2.1.5 on 2019-02-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeriya', '0002_auto_20190226_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeriya',
            options={},
        ),
        migrations.RemoveField(
            model_name='galeriya',
            name='publish',
        ),
    ]
