# Generated by Django 2.1.5 on 2019-01-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190124_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reqem',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
