# Generated by Django 2.1.5 on 2019-01-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_reqem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='reqem',
            field=models.IntegerField(),
        ),
    ]
