# Generated by Django 2.1.5 on 2019-01-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_reqem'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='say',
            field=models.IntegerField(default=1, verbose_name='baxish sayi'),
            preserve_default=False,
        ),
    ]
