# Generated by Django 2.1.5 on 2019-01-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_say'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='say',
        ),
    ]
