# Generated by Django 2.1.5 on 2019-02-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blog_say'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Başlıq'),
        ),
    ]
