# Generated by Django 2.1.5 on 2019-01-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='kurs adi')),
                ('content', models.TextField(blank=True, verbose_name='haqqinda')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('height_field', models.IntegerField(default=0)),
                ('publish', models.DateTimeField(auto_now=True, verbose_name='tarix')),
            ],
            options={
                'ordering': ['-publish', 'id'],
            },
        ),
    ]
